SELECT INS.ANIMAL_ID, INS.NAME from ANIMAL_INS as INS
LEFT JOIN ANIMAL_OUTS as OUTS on (INS.ANIMAL_ID = OUTS.ANIMAL_ID)
WHERE OUTS.ANIMAL_ID is not null
ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC
LIMIT 2