SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME FROM ANIMAL_OUTS as OUTS
LEFT JOIN ANIMAL_INS as INS on (INS.ANIMAL_ID = OUTS.ANIMAL_ID) 
WHERE (OUTS.SEX_UPON_OUTCOME like '%Spayed%' or OUTS.SEX_UPON_OUTCOME like '%Neutered%') and (INS.SEX_UPON_INTAKE like '%Intact%')
ORDER BY ANIMAL_ID ASC